ACJ/Models/ErrorViewModel.cs
using System;

namespace ACJ.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ACJ/Models/QuoteModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ACJ.Models
{
    public class QuoteModel
    {
        public string Content { get; set; }
        public string Author { get; set; }
    }
}

ACJ/Controllers/AliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ACJ.Controllers
{
    public class AliController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ACJ/Controllers/ClaraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using ACJ.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ACJ.Controllers
{
    public class ClaraController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var quote = new QuoteModel();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("https://api.quotable.io/random"))
                {
                    var content = await response.Content.ReadAsStringAsync();
                    quote = JsonConvert.DeserializeObject<QuoteModel>(content);
                }
            }
            return View(quote);
        }
    }
}

ACJ/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ACJ.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ACJ.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ACJ/Controllers/JesperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ACJ.Controllers
{
    public class JesperController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ACJ/Views/Ali/Index.cshtml
@{
    ViewData["Title"] = "Ali";
}
<link href="~/css/alisStyle.css" rel="stylesheet"/>
<div class="header">
    <div class="name">
        <h1>
            <strong>Ali Mesbahi</strong>
        </h1>
        <h2>
            <strong>Azure cloud utvecklare</strong>
        </h2>
    </div>
    <div class="image-background">
        <div class="image-placeholder">
            <div class="image-admin"></div>
        </div>
    </div>
</div>
<div class="content">
    <div class="left-panel">
        <div class="social-media">
            <h3>Group members</h3>
            <hr />
            <ul>
                <li>
                    <a href="@Url.Action("Index","Clara")">Clara Fred</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Jesper")">Jesper Norman</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Ali")">Ali Mesbahi</a>
                </li>
            </ul>
            <br />
            <h3>Github</h3>
            <ul>
                <li>
                <a href="https://github.com/clarafred/ACJ.git" target="_blank">Group's Repository</a>
                </li>
                <li>
                <a href="https://github.com/90rimane/ACJ.git" target="_blank">Ali's Repository</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="right-panel">
        <div class="education">
            <i class="material-icons">school</i>
            <h3>Education</h3>
            <hr />
            <div class="education-item">
                <h4>Jensen Yrkeshögskolan</h4>
                <ul>
                    <li>Azur cloud utvecklare, 2020 - 2022</li>
                </ul>
            </div>
            <div class="education-item">
                <h4>Hermods AB</h4>
                <ul>
                    <li>Webb utveckling 1, 2019 - 2019</li>
                    <li>Programmering 1, 2019 - 2019</li>
                </ul>
            </div>
            <div>
                <h4>Islamshar Universitiet/ IRAN</h4>
                <ul>
                    <li>Mechanical engineering, 2008 - 2012 (<a href="" target="_blank">More Info</a>)</li>
                </ul>
            </div>
        </div>
        <div class="work-experience">
            <i class="material-icons">business_center</i>
            <h3>Work Experience</h3>
            <hr />
            <div class="work-item">
                <h4>Staff Accountant II</h4>
                <div class="work-item-subtitle">
                    <h5 class="work-company">The Fresh Market, Inc.</h5>
                    <h5 class="work-year"> 2019 - 2019</h5>
                </div>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="work-item">
                <h4>Property Accountant</h4>
                <div class="work-item-subtitle">
                    <h5 class="work-company">Koury Corporation</h5>
                    <h5 class="work-year">August 2017 - January 2019</h5>
                </div>
                <p>
                    Lorems ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>

        </div>

    </div>

</div>
<div class="footer-alispage">
    <div class="footer-text"><p>| Projekarbete | Grupp 2 | Ali, Clara, Jesper |</p><br/>
    </div>
    
</div>

ACJ/Views/Clara/Index.cshtml
@model QuoteModel

@{
    ViewData["Title"] = "Clara";
}

@section css {
    <link rel="stylesheet" href="~/css/clara.css" />
}
<div>
    <h1 class="display-4 text-center top">HIKING IN SWEDEN</h1>
    <div class="header-bar"></div>
</div>

<div class="pine-icon text-center">
    <img src="https://image.flaticon.com/icons/png/512/66/66715.png"/>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm trans">
            <h3 class="text-center">THE WEATHER</h3>
            <p>
                Above the Arctic Circle, winter is severe with temperatures going below -30°C, while summer temperatures here,
                and in the rest of the country, regularly hit +20°C. In the south,
                winter is generally mild with an average temperature above 0°C/32°F degrees.
                <br /><br />
                Sweden's northerly position has a definite summer advantage in that temperatures are rarely extreme and humidity
                levels are not high. For up to date weather information for Sweden you should visit the SMHI site, where you'll
                also find maps and graphs with weather information: <a href="http://smhi.se">SMHI.SE</a>
                <br /><br />
                So, no Polar bears we’re afraid, just the wonderful Swedish weather and all the fantastic things you can do in it.
            </p>
        </div>

        <div class="col-sm trans">
            <h3 class="text-center">TOP TRAILS</h3>
            <p><strong>> </strong><a href="https://visitsweden.com/where-to-go/northern-sweden/swedish-lapland/kings-trail-kungsleden/">THE KING'S TRAIL (north)</a></p>
            <p><strong>> </strong><a href="https://www.utvandrarleden.se/en-GB">THE EMIGRANT TRAIL (western)</a></p>
            <p><strong>> </strong><a href="https://skaneleden.se/en/#googtrans(sv|en)">SKÅNELEDEN TRAIL (south)</a></p>
        </div>

        <div class="col-sm trans text-center">
            <h3>PLAN YOUR TRIP</h3>
            <p>
                <a href="https://foxtrail.fjallraven.com/articles/prepare-for-fjallraven-classic-part-2-what-to-pack/">
                    <img src="https://static.thenounproject.com/png/16771-200.png" />
                    <br />WHAT TO BRING?

                </a>
                <br />
                <br />
            </p>
            <p>
                <a href="https://www.nationalparksofsweden.se/">
                    <img src="https://image.flaticon.com/icons/png/512/92/92726.png" />
                    <br />NATIONAL PARKS
                </a>
            </p>
            <p>
                <a href="https://visitsweden.com/explore-map/">
                    <img src="http://simpleicon.com/wp-content/uploads/map-8.png" />
                    <br />MAP
                </a>
                <br />
                <br />
            </p>
        </div>
    </div>
</div>

<div class="quote text-center">
    @Model.Content - <i>@Model.Author</i>
</div>

ACJ/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "ACJ";
}

<div class="text-center">
    <h1 class="display-4">WELCOME!</h1>
    <p class="members-list">To the beautiful website of group 2 - Ali, Clara & Jesper.</p>
</div>

ACJ/Views/Jesper/Index.cshtml
@{
    ViewData["Title"] = "Jesper";
}

@section css {
    <link rel="stylesheet" href="~/css/jesper.css" />
}

<div class="text-center">
    <h1 class="display-4">FIND YOUR SKI RESORT</h1>
</div>
<div class="Empty">

</div>

<div id="wrapper">
    <div id="Left">
        <div class="Skiresortbox">
            <p>
                <h2> Länkar till skidområden i norden:</h2>
                <h5>
                    <a href="https://www.skidorter.net/sverige.php"><br />Svenska skidorter</a>
                </h5>
                <h5>
                    <a href="https://www.skidorter.net/norge.php"><br />Norska skidorter</a>
                </h5>
                <h5>
                    <a href="https://www.skidorter.net/finland.php"><br />Finska skidorter</a>
                </h5>
            </p>
        </div>
        <div class="Weatherbox">
            <h4> Hämta snö prognoser </h4>
            <h5>
                <a href="https://se.snow-forecast.com/maps"><br />SnowForecast</a>
            </h5>
            <h5>
                <a href="https://www.skiinfo.se/sverige/snoprognos.html"><br />Vart ska det snöa</a>
            </h5>
        </div>
        <div class="special">
            <h4>3D kartor</h4>
            <h5>
                <a href="https://maps.snowzat.com"><br />Snowzat</a>
            </h5>
        </div>
    </div>

    <div id="Right">
        <div class="Googlecontainer">
            <div class="Googlemapsbox">
                <h4> GoogleMaps</h4>
                <div id="googleMap" style="width:100%;height:400px;">
                </div>
                <script>
                    var map;
                    function myMap() {
                        const coordinate = { lat: 57.1057412, lng: 12.2502949 };
                        var mapProp = {
                            center: new google.maps.LatLng(57.1057412, 12.2502949),
                            mapTypeId: google.maps.MapTypeId.ROADMAP,
                            zoom: 12
                        };
                        map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
                        const marker = new google.maps.Marker({
                            position: coordinate,
                            map: map,
                        });
                    }

                    function search() {

                        var searchInput = document.getElementById('searchInput').value
                        var url = 'https://nominatim.openstreetmap.org/search?q=' + searchInput + '&format=json'
                        console.log(url);

                        fetch(url)
                            .then(response => response.json())
                            .then(data =>
                                redrawMap(data[0].lat, data[0].lon));

                    }

                    function redrawMap(lat, long) {
                        console.log("Coordinates from api, Latitude:" + lat + " Longitude:" + long);

                        var panPoint = new google.maps.LatLng(lat, long);
                        map.panTo(panPoint);

                        var coordinate = { lat: 57.1057412, lng: 12.2502949 };
                        coordinate.lat = parseFloat(lat);
                        coordinate.lng = parseFloat(long);

                        const marker = new google.maps.Marker({
                            position: coordinate,
                            map: map,
                        });
                    }

                </script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCCug0b5_DVdle-tFS42V13CTeGJYC_ecE&callback=myMap"></script>
            </div>
        </div>
        <div class="searchbox">
            <input type="text" id="searchInput" placeholder="Search for place.." name="search2">
            <button type="button" onclick="search();"> GO </button>
        </div>
    </div>
</div>

<div class="Empty">

</div>

ACJ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACJ</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("css", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ACJ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ali" asp-action="Index">Ali</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clara" asp-action="Index">Clara</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jesper" asp-action="Index">Jesper</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ACJ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>